# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticsearchDocumentCleaner < Formula
  desc "elasticsearch-document-cleaner cleans documents in an Elasticsearch index with specific conditions"
  homepage "https://github.com/bilalcaliskan/elasticsearch-document-cleaner"
  version "0.1.16"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/elasticsearch-document-cleaner/releases/download/v0.1.16/elasticsearch-document-cleaner_0.1.16_darwin_x86_64.tar.gz"
    sha256 "e4c24aeaf21b2d90dfff4d3ca272772f2ce6d3ddad582ca9d227c8337944a028"

    def install
      bin.install "elasticsearch-document-cleaner"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ElasticsearchDocumentCleaner
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/elasticsearch-document-cleaner/releases/download/v0.1.16/elasticsearch-document-cleaner_0.1.16_linux_x86_64.tar.gz"
      sha256 "94777373d661d8a73bea507ab2891ce34d8275a49cecc1a07e46ffe2967be69b"

      def install
        bin.install "elasticsearch-document-cleaner"
      end
    end
  end
end
