# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticsearchDocumentCleaner < Formula
  desc "elasticsearch-document-cleaner cleans documents in an Elasticsearch index with specific conditions"
  homepage "https://github.com/bilalcaliskan/elasticsearch-document-cleaner"
  version "0.1.15"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/elasticsearch-document-cleaner/releases/download/v0.1.15/elasticsearch-document-cleaner_0.1.15_darwin_x86_64.tar.gz"
    sha256 "b0768e77e73c8ccb1e62fa098616b14c65a2c9a098e6ff1a714ff1b489209ea8"

    def install
      bin.install "elasticsearch-document-cleaner"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ElasticsearchDocumentCleaner
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/elasticsearch-document-cleaner/releases/download/v0.1.15/elasticsearch-document-cleaner_0.1.15_linux_x86_64.tar.gz"
      sha256 "2371a616d95ebc49d416f0a4511f93596ea029da1e6c84471de59bf82828358c"

      def install
        bin.install "elasticsearch-document-cleaner"
      end
    end
  end
end
