# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubePodTerminator < Formula
  desc "kube-pod-terminator discovers pods which are at 'Evicted' or 'Terminating' state and clears them from Kubernetes cluster"
  homepage "https://github.com/bilalcaliskan/kube-pod-terminator"
  version "3.0.1"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/kube-pod-terminator/releases/download/v3.0.1/kube-pod-terminator_3.0.1_darwin_amd64.tar.gz"
    sha256 "395f32266d8f14a3dfc1c7420b7318a812bfebc479046daf0d0ae264bc38d6eb"

    def install
      bin.install "kube-pod-terminator"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the KubePodTerminator
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/kube-pod-terminator/releases/download/v3.0.1/kube-pod-terminator_3.0.1_linux_amd64.tar.gz"
      sha256 "e72e4d7e2d16bd335cf8995727fa2fa6aca6363652cd472ddf46446827faee89"

      def install
        bin.install "kube-pod-terminator"
      end
    end
  end
end
