# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubePodTerminator < Formula
  desc "kube-pod-terminator discovers pods which are at 'Evicted' or 'Terminating' state and clears them from Kubernetes cluster"
  homepage "https://github.com/bilalcaliskan/kube-pod-terminator"
  version "2.1.10"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/kube-pod-terminator/releases/download/v2.1.10/kube-pod-terminator_2.1.10_darwin_amd64.tar.gz"
    sha256 "e289b7af1f3456eb46f34bf1ac32828631052eebb71ae2db26272086271c5625"

    def install
      bin.install "kube-pod-terminator"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the KubePodTerminator
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/kube-pod-terminator/releases/download/v2.1.10/kube-pod-terminator_2.1.10_linux_amd64.tar.gz"
      sha256 "84b125a57cc3522a9429d3532c7e14f780fbc539833ea6c61493b4625fc540d6"

      def install
        bin.install "kube-pod-terminator"
      end
    end
  end
end
