# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxConfGenerator < Formula
  desc "nginx-conf-generator gets the port of NodePort type services from a cluster and manages Nginx configuration"
  homepage "https://github.com/bilalcaliskan/nginx-conf-generator"
  version "5.0.3"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/nginx-conf-generator/releases/download/v5.0.3/nginx-conf-generator_5.0.3_darwin_x86_64.tar.gz"
    sha256 "54b1f387a5f8e5012063c802215698722319a9680ff944ff7c6210529e960a24"

    def install
      bin.install "nginx-conf-generator"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the NginxConfGenerator
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/nginx-conf-generator/releases/download/v5.0.3/nginx-conf-generator_5.0.3_linux_x86_64.tar.gz"
      sha256 "d00ce80a6e6498dd71b5eee2bd4f8af9d0207383f2edbe145810695280a74f2c"

      def install
        bin.install "nginx-conf-generator"
      end
    end
  end
end
