# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OreillyTrial < Formula
  desc "oreilly-trial creates a trial Oreilly account for 10 days"
  homepage "https://github.com/bilalcaliskan/oreilly-trial"
  version "0.1.92"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/oreilly-trial/releases/download/v0.1.92/oreilly-trial_0.1.92_darwin_x86_64.tar.gz"
    sha256 "5ec4cc90794c5edb553ef27b5e31de0bad5fa3b54644ada463be77d17e87611e"

    def install
      bin.install "oreilly-trial"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OreillyTrial
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/oreilly-trial/releases/download/v0.1.92/oreilly-trial_0.1.92_linux_x86_64.tar.gz"
      sha256 "d06d6b2806fb9f834b87c8c9c5ccad46c45ae4adac7ae1dc7b6547db622502b5"

      def install
        bin.install "oreilly-trial"
      end
    end
  end
end
