# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OreillyTrial < Formula
  desc "oreilly-trial creates a trial Oreilly account for 10 days"
  homepage "https://github.com/bilalcaliskan/oreilly-trial"
  version "0.1.91"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/oreilly-trial/releases/download/v0.1.91/oreilly-trial_0.1.91_darwin_x86_64.tar.gz"
    sha256 "09be75f50566b7b118dcf6b27c398074e4758ffa6add4581246319eedb063000"

    def install
      bin.install "oreilly-trial"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OreillyTrial
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/oreilly-trial/releases/download/v0.1.91/oreilly-trial_0.1.91_linux_x86_64.tar.gz"
      sha256 "149718865717b0e517b8e7f4577876fda5ab6f05928932541ea0bee41fe69c58"

      def install
        bin.install "oreilly-trial"
      end
    end
  end
end
