# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OreillyTrial < Formula
  desc "oreilly-trial creates a trial Oreilly account for 10 days"
  homepage "https://github.com/bilalcaliskan/oreilly-trial"
  version "0.1.90"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/oreilly-trial/releases/download/v0.1.90/oreilly-trial_0.1.90_darwin_x86_64.tar.gz"
    sha256 "0801ce2112e3114e66bf87484d43c18ed8deafa6e3ffdb15279d057733251276"

    def install
      bin.install "oreilly-trial"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OreillyTrial
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/oreilly-trial/releases/download/v0.1.90/oreilly-trial_0.1.90_linux_x86_64.tar.gz"
      sha256 "1e8c279bc35a03e3002fd2da2b87190bc716364f96cb66036e74e3589a76bf7d"

      def install
        bin.install "oreilly-trial"
      end
    end
  end
end
