# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Cleaner < Formula
  desc "s3-cleaner does something"
  homepage "https://github.com/bilalcaliskan/s3-cleaner"
  version "0.2.7"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-cleaner/releases/download/v0.2.7/s3-cleaner_0.2.7_darwin_x86_64.tar.gz"
    sha256 "fe661c7b7b4e9e1f5cf6190334fab633629c52906541399920b05bc5d4176ff3"

    def install
      bin.install "s3-cleaner"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3Cleaner
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-cleaner/releases/download/v0.2.7/s3-cleaner_0.2.7_linux_x86_64.tar.gz"
      sha256 "648caad88746564f10724fbc5183bac604ec622d16248d5831098c2a4aa9f8e2"

      def install
        bin.install "s3-cleaner"
      end
    end
  end
end
