# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Cleaner < Formula
  desc "s3-cleaner does something"
  homepage "https://github.com/bilalcaliskan/s3-cleaner"
  version "0.1.2"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-cleaner/releases/download/v0.1.2/s3-cleaner_0.1.2_darwin_x86_64.tar.gz"
    sha256 "279a90d426f0b83c64a3edf007eda6b1bd3f44c6d3a8ab9a121b6e8d359f2ae8"

    def install
      bin.install "s3-cleaner"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3Cleaner
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-cleaner/releases/download/v0.1.2/s3-cleaner_0.1.2_linux_x86_64.tar.gz"
      sha256 "e678514c8fa7cf1f13d466afd10a622eefe8b031f0b6903f2e4c65257e52957c"

      def install
        bin.install "s3-cleaner"
      end
    end
  end
end
