# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Cleaner < Formula
  desc "s3-cleaner does something"
  homepage "https://github.com/bilalcaliskan/s3-cleaner"
  version "0.1.0"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-cleaner/releases/download/v0.1.0/s3-cleaner_0.1.0_darwin_x86_64.tar.gz"
    sha256 "89ca9f15b361756a08ea6008e861c3f03d1f8d9ab8bfcf0c96d73a6b83d4e1fd"

    def install
      bin.install "s3-cleaner"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3Cleaner
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-cleaner/releases/download/v0.1.0/s3-cleaner_0.1.0_linux_x86_64.tar.gz"
      sha256 "5a7db7a3068a526f2fb185bafa6457f68afcb6e13e011491ec69b4d6762e6e37"

      def install
        bin.install "s3-cleaner"
      end
    end
  end
end
