# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Manager < Formula
  desc "s3-manager does something"
  homepage "https://github.com/bilalcaliskan/s3-manager"
  version "1.0.0"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-manager/releases/download/v1.0.0/s3-manager_1.0.0_darwin_x86_64.tar.gz"
    sha256 "774fb65f8d8b6fcb17e90dc58eaa6700352bc1aa0349778eaaa33df384733746"

    def install
      bin.install "s3-manager"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3Manager
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-manager/releases/download/v1.0.0/s3-manager_1.0.0_linux_x86_64.tar.gz"
      sha256 "3cbd4be20cc2704b3775e3514ad40bfce179d706fc90414942db9ed515af205a"

      def install
        bin.install "s3-manager"
      end
    end
  end
end
