# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Manager < Formula
  desc "s3-manager does something"
  homepage "https://github.com/bilalcaliskan/s3-manager"
  version "0.0.2"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-manager/releases/download/v0.0.2/s3-manager_0.0.2_darwin_x86_64.tar.gz"
    sha256 "40c836d93e541d1bdb5633f55f9b18944bcecbc07e5e127dac34cbd5bd6321f7"

    def install
      bin.install "s3-manager"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3Manager
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-manager/releases/download/v0.0.2/s3-manager_0.0.2_linux_x86_64.tar.gz"
      sha256 "a4e215aa2ebb283b746d1e347f1969a5b519855806c23f20eebbc1929fa061c8"

      def install
        bin.install "s3-manager"
      end
    end
  end
end
