# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3SubstringFinder < Formula
  desc "s3-substring-finder accesses to S3 buckets and finds txt files which contains specific substring"
  homepage "https://github.com/bilalcaliskan/s3-substring-finder"
  version "2.1.7"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-substring-finder/releases/download/v2.1.7/s3-substring-finder_2.1.7_darwin_x86_64.tar.gz"
    sha256 "2e2523cb4727594a1d215d9eee01bb7053e303e89d3a896c86c5c46dc84b1da4"

    def install
      bin.install "s3-substring-finder"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3SubstringFinder
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-substring-finder/releases/download/v2.1.7/s3-substring-finder_2.1.7_linux_x86_64.tar.gz"
      sha256 "df54bed334fdb27587f670ca889be11bce4a3b811fefb60a3eb71b032cb4b50c"

      def install
        bin.install "s3-substring-finder"
      end
    end
  end
end
