# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3SubstringFinder < Formula
  desc "s3-substring-finder accesses to S3 buckets and finds txt files which contains specific substring"
  homepage "https://github.com/bilalcaliskan/s3-substring-finder"
  version "2.1.6"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-substring-finder/releases/download/v2.1.6/s3-substring-finder_2.1.6_darwin_x86_64.tar.gz"
    sha256 "892a2167566a827af3b8a6b6ae6b13955998c6800e423f4fc79e036d08c233cf"

    def install
      bin.install "s3-substring-finder"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3SubstringFinder
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-substring-finder/releases/download/v2.1.6/s3-substring-finder_2.1.6_linux_x86_64.tar.gz"
      sha256 "3aadf7b43f0d3d82d6ea0016a64008a21700839a3ba7d2c03511025666347dff"

      def install
        bin.install "s3-substring-finder"
      end
    end
  end
end
