# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3SubstringFinder < Formula
  desc "s3-substring-finder accesses to S3 buckets and finds txt files which contains specific substring"
  homepage "https://github.com/bilalcaliskan/s3-substring-finder"
  version "1.1.9"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/s3-substring-finder/releases/download/v1.1.9/s3-substring-finder_1.1.9_darwin_x86_64.tar.gz"
    sha256 "f2bfe1e1453f911d6496976bbbc94bdac29dfd7c20bb70e13fc09d21380c7047"

    def install
      bin.install "s3-substring-finder"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the S3SubstringFinder
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/s3-substring-finder/releases/download/v1.1.9/s3-substring-finder_1.1.9_linux_x86_64.tar.gz"
      sha256 "f4ef839432e6913be9d21346e9d85b7afab8d9c6ba6855811ef28b2ef512ba69"

      def install
        bin.install "s3-substring-finder"
      end
    end
  end
end
