# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SynFlood < Formula
  desc "syn-flood starts a syn flood attack with raw sockets. created for learning low level network ops"
  homepage "https://github.com/bilalcaliskan/syn-flood"
  version "1.0.46"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/syn-flood/releases/download/v1.0.46/syn-flood_1.0.46_darwin_x86_64.tar.gz"
    sha256 "04500a03096243669028c16659237fa896502e221b9e63d98ee19646015cdef8"

    def install
      bin.install "syn-flood"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SynFlood
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/syn-flood/releases/download/v1.0.46/syn-flood_1.0.46_linux_x86_64.tar.gz"
      sha256 "8e0cbba81ef95d83e9f27f04aaef9c7f757f2c61e9efff0b4c1ad989bc7416ee"

      def install
        bin.install "syn-flood"
      end
    end
  end
end
