# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SynFlood < Formula
  desc "syn-flood starts a syn flood attack with raw sockets. created for learning low level network ops"
  homepage "https://github.com/bilalcaliskan/syn-flood"
  version "1.1.1"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/syn-flood/releases/download/v1.1.1/syn-flood_1.1.1_darwin_x86_64.tar.gz"
    sha256 "b440342108d138f64f197390253ef68e550de9284900105a4c9d88ea8f640158"

    def install
      bin.install "syn-flood"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SynFlood
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/syn-flood/releases/download/v1.1.1/syn-flood_1.1.1_linux_x86_64.tar.gz"
      sha256 "77370b0f16d02d9e1d58edb4980f63fb6207667d0800e516224e3b7ff7b2b67b"

      def install
        bin.install "syn-flood"
      end
    end
  end
end
