# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SynFlood < Formula
  desc "syn-flood starts a syn flood attack with raw sockets. created for learning low level network ops"
  homepage "https://github.com/bilalcaliskan/syn-flood"
  version "1.0.44"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/syn-flood/releases/download/v1.0.44/syn-flood_1.0.44_darwin_x86_64.tar.gz"
    sha256 "f268326af16aba3c82c264f375ce2c00a01c81ea220d454b464710c00298bff2"

    def install
      bin.install "syn-flood"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SynFlood
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/syn-flood/releases/download/v1.0.44/syn-flood_1.0.44_linux_x86_64.tar.gz"
      sha256 "5df5b8d5ce1f90ee0e1d15ec64d6fd86f414b1014e141d025a160acd328a4ba0"

      def install
        bin.install "syn-flood"
      end
    end
  end
end
