# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TcpProxy < Formula
  desc "simple TCP proxy written with Golang using built-in net package"
  homepage "https://github.com/bilalcaliskan/tcp-proxy"
  version "0.1.15"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/tcp-proxy/releases/download/v0.1.15/tcp-proxy_0.1.15_darwin_x86_64.tar.gz"
    sha256 "287f71b9cb341c44eb24e8bdfe0e27cb3c8ddcbabe42d21f15aedc18c6bee985"

    def install
      bin.install "tcp-proxy"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TcpProxy
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/tcp-proxy/releases/download/v0.1.15/tcp-proxy_0.1.15_linux_x86_64.tar.gz"
      sha256 "44a3f51cd7f6dbe84870dfbbfefe0b93b7685838797637bb0acf0a77c8f9c09d"

      def install
        bin.install "tcp-proxy"
      end
    end
  end
end
