# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TcpProxy < Formula
  desc "simple TCP proxy written with Golang using built-in net package"
  homepage "https://github.com/bilalcaliskan/tcp-proxy"
  version "0.1.16"
  license "apache-2.0"

  on_macos do
    url "https://github.com/bilalcaliskan/tcp-proxy/releases/download/v0.1.16/tcp-proxy_0.1.16_darwin_x86_64.tar.gz"
    sha256 "78255e7a926d296110f5bbf86784b92a9e8af7baaa8d240dad3c1b3231fbf869"

    def install
      bin.install "tcp-proxy"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TcpProxy
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bilalcaliskan/tcp-proxy/releases/download/v0.1.16/tcp-proxy_0.1.16_linux_x86_64.tar.gz"
      sha256 "fd32b8f34b4c92deb7fb8d5eb0399cb5fe1cf18b2c725ec9d08c86d235a91b31"

      def install
        bin.install "tcp-proxy"
      end
    end
  end
end
